server:
  port: 8082

spring:
  application:
    name: family-finance
  aop:
    auto: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
